### PR TITLE
[KNI] WIP: introducing the staging plugin

### PR DESCRIPTION
**Pull request by ffromani**
A very ambitious but important goal of this fork (in github sense) is
to keep full compatibility with the upstream project, and to have
very obvious, crystal clear paper trail about changes.
Ideally, we would like to have the very same u/s commits (SHA-level
identical) and to add on top of that the bits and pieces we need.

At the same time, another key goal is to carry patches u/s is not (yet)
ready to accept, to experiment and/or to full fill KNI specific needs.

These two goals conflict to a significant extent. Carry u/s patches
out of order (or which u/s didn't accept) alter the git history,
and this makes harder or impossible to keep 1:1 relationship
between u/s commits and kni commits.

It's possible that in the future we will need to relax this constraint,
and to deal the fact that we cannot any longer just have SHA-level
identity between the histories of these two repos.

But we need to try hard anyway.
A possible way out is to keep a staging clone of the
noderesourcetopology package, to hold here the carried patches.
Over time, u/s (hopefully) accepts these changes and/or will provide
better replacements; in these cases we will resync or reset the
staging area periodically to realign with the 'stable' (as in
'non-staging') area.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
For consistency with the k8s can we use `staging/github.com/<organization_name>/<repo_name>` ?

**Comment by ffromani** [comment]
> For consistency with the k8s can we use `staging/github.com/<organization_name>/<repo_name>` ?

Sure, that's an option. I'm evaluating the layout atm. I'm not sure "staging" actually means what I mean here, nor that the same layout is relevant here. Clarifying this is indeed the blocker issue for this PR to move forward (or not), so thanks for raising!

**Comment by ffromani** [comment]
/hold
see: https://github.com/openshift-kni/scheduler-plugins/pull/17#issuecomment-1004202215

**Comment by ffromani** [comment]
What I called "staging" should probably be called "experimental". Still thinking about it. If the name sounds a little scary, not a big deal :)

**Comment by cynepco3hahue** [comment]
> What I called "staging" should probably be called "experimental". Still thinking about it. If the name sounds a little scary, not a big deal :)

We can use the OpenShift approach, under the Kubernetes openshift fork, the stuff that is only related to the openshift has openshift prefix for example https://github.com/openshift/kubernetes/tree/master/openshift-kube-apiserver

**Comment by ffromani** [comment]
yes, I'm considering these names for the subtree:
```
kni
extras
staging <- not the best, see above
experimental <- too scary
```

Preferring for `kni` atm

**Comment by Tal-or** [comment]
What does the [CARRY] label mean?

**Comment by ffromani** [comment]
> What does the [CARRY] label mean?

borrowing (and abusing a bit) the OCP nomenclature, means we carry on our own a patch which is not merged (yet) u/s

**Comment by ffromani** [comment]
replaced by #18

**Pull request closed without merging**
