### PR TITLE
[release-4.10][manual][PR#371] implement strict alignment check for the noderesourcetopology filter …

### PR DESCRIPTION
**Pull request by ffromani**
…plugin (#347)

* nrt: filter: use IsZero()

Use resource.Quantity.IsZero() helper instead of comparing
with zero quantity. This is a bit nicer to read, but most notably
saves us a relatively costly MustParse call in each function run.

No intended changes in behaviour.

Signed-off-by: Francesco Romani <fromani@redhat.com>

* nrt: filter: isolate the per-NUMA decision logic

Extract the inner logic to check if a NUMA Node is suitable
in its own function.
This change enables further cleanups, and easier changing
of the filtering logic.
It will also make adding more logs easier down the line

No intended changes in behaviour.

Signed-off-by: Francesco Romani <fromani@redhat.com>

* nrt: filter: split complex if in a sequence of ifs

Split the complex condition, to make the code easier
to read, change, and possibly add (and log) the
NUMA node reject reason in the future.

No intended change in behaviour.

Signed-off-by: Francesco Romani <fromani@redhat.com>

* nrt: filter: qos=guaranteed requires align for mem/hp

In kubernetes >= 1.23, which is already out, we can
depend on the memory manager for alignment of memory and
hugepages. So we make the alignment check consistent to
what we do for CPU.

Signed-off-by: Francesco Romani <fromani@redhat.com>

* nrt: filter: make test more extendible

Make it easier to add new test cases without intended
changes in behaviour

Signed-off-by: Francesco Romani <fromani@redhat.com>

* nrt: flter: add more test cases

Improve the test coverage of the filter plugin

Signed-off-by: Francesco Romani <fromani@redhat.com>

<!--  Thanks for sending a pull request!  Here are some tips for you:

1. If this is your first time, please read our contributor guidelines: https://git.k8s.io/community/contributors/guide/first-contribution.md#your-first-contribution and developer guide https://git.k8s.io/community/contributors/devel/development.md#development-guide
2. Please label this pull request according to what type of issue you are addressing, especially if this is a release targeted pull request. For reference on required PR/issue labels, read here:
https://git.k8s.io/community/contributors/devel/sig-release/release.md#issuepr-kind-label
3. Ensure you have added or ran the appropriate tests for your PR: https://git.k8s.io/community/contributors/devel/sig-testing/testing.md
4. If you want *faster* PR reviews, read how: https://git.k8s.io/community/contributors/guide/pull-requests.md#best-practices-for-faster-reviews
5. If the PR is unfinished, see how to mark it: https://git.k8s.io/community/contributors/guide/pull-requests.md#marking-unfinished-pull-requests

### CODE REVIEW

**Comment by Tal-or** [comment]
Is there a reason for combining all the commits together?

**Comment by ffromani** [comment]
> Is there a reason for combining all the commits together?

it was squashed upstream (maintainer decision - I don't have strong feelings about it). I'm cherry-picking the u/s commit verbatim.

**Comment by ffromani** [comment]
the branch name is misleading: that was actually PR347 upstream

**Pull request merged**
