### PR TITLE
[KNI] go1.18: Update go.mod

### PR DESCRIPTION
**Pull request by swatisehgal**
Move from go 1.17 to go1.18
    Ran `go mod tidy`

Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

### CODE REVIEW

**Comment by ffromani** [comment]
the weird thing is that actually https://github.com/openshift-kni/numaresources-operator/pull/295 merged without complains. That's the behaviour I would have expected. `prow` takes the settings from the repo HEAD, this means we cannot switch the compiler AND the dependency in the same go - the `Dockerfile.tools` will be the one from the repo - not the changed one. The solution is to split the PR in two: 1. first update the compiler (should pass just fine) 2. then once 1 merged send another PR bumping the go.mod to 1.18

**Comment by ffromani** [comment]
point in case: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-kni_numaresources-operator/295/pull-ci-openshift-kni-numaresources-operator-main-images/1527304939020226560/artifacts/build-logs/root.log

**Comment by swatisehgal** [comment]
Ah okay, that makes sense. I will split this into two PRs.

**Comment by ffromani** [comment]
unfortunately you'll also need a rebase (that's the easiest way)

**Comment by swatisehgal** [comment]
https://github.com/openshift-kni/scheduler-plugins/pull/38 should unblock this PR.

**Pull request merged**
