### PR TITLE
Resync 20211223

### PR DESCRIPTION
**Pull request by Tal-or**
Resync the KNI repo with the u/s changes as-is today.
The compilation, unit tests, and integration tests were passed.
Updated the resync info under the ```RESYNC.md``` file

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold
until CI get fixed

**Comment by ffromani** [comment]
/hold cancel
but we will need a rebase on top of the current master branch

**Comment by Tal-or** [comment]
/hold
the merge got mixed with the rebase

**Comment by Tal-or** [comment]
This branch was polluted by the rebase

**Pull request closed without merging**
