### PR TITLE
cleanup: revert: prepare for resync release-4.13 branch 

### PR DESCRIPTION
**Pull request by Tal-or**
This PR contains a set of revert commits.
Those commits are reverting  commits that would avoid 
clean resync of `release-4.12` with `release-4.13` branch.

### CODE REVIEW

**Comment by ffromani** [comment]
I would have done differently but this looks like a legit and equivalent alternate approach. I'll have a deep look soon(ish)

**Comment by Tal-or** [comment]
Eventually there was no need to revert one by one. reverting the "kube deps bump" commit  unblocked the revert on #67

**Pull request merged**
