### PR TITLE
[KNI] [release-4.12] resync with release-4.13 20230523

### PR DESCRIPTION
**Pull request by Tal-or**
Align release-4.12 branch with same u/s changes release-4.13 branch has

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold cancel
unit-test + integration tests passed successfully

**Comment by ffromani** [comment]
thanks! looks good. The original plan was to align to 4.13.0, but upstream went too far.  We should stop at bc9480d3 included and evaluate later if we decide to consume 1.26.z or if we stay on 1.25. Could you please update this PR accordingly?

**Comment by ffromani** [comment]
closed by mistake

**Comment by Tal-or** [comment]
updated PR: https://github.com/openshift-kni/scheduler-plugins/pull/92

**Pull request closed without merging**
