### PR TITLE
doc: resync.md: Document release branch upstream resync strategy

### PR DESCRIPTION
**Pull request by swatisehgal**
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/lgtm
/approve

**Comment by ffromani** [comment]
looks fine, but I can't help but wonder why the `commit-check` lane passed without the [KNI] tag. Let's check and then we can merge.

**Comment by ffromani** [comment]
here's why: https://github.com/openshift-kni/scheduler-plugins/blob/master/hack-kni/verify-commits.sh#L15
we're probably doing it slightly wrong and being saved by the discipline and the process here. @swatisehgal could you please add the `[KNI]` tag to the the commit message here? we should revisit the way we check on a separate PR/discussion

**Comment by swatisehgal** [comment]
It is to do with the branch name I picked (resync-update) :) 

We allow commit non enforcement in case of resync updates:
https://github.com/openshift-kni/scheduler-plugins/blob/master/hack-kni/verify-commits.sh#L14-L18

**Comment by ffromani** [comment]
/lgtm
/approve
Thanks @swatisehgal for the update. This PR is fine as it is. Let's discuss stricter/better commit check offline.

**Pull request merged**
