### PR TITLE
Resync 20220623

### PR DESCRIPTION
**Pull request by swatisehgal**
Resync with upstream 20220623.

### CODE REVIEW

**Review by Tal-or — COMMENTED** [review]
Why do we need the vendor update? are these libs not being used u/s as well?

**Comment by swatisehgal** [comment]
Upstream doesn't seem to have a vendor directory but we do. There was a change made [here](https://github.com/openshift-kni/scheduler-plugins/pull/41/commits/b73694f2dee07add60e79fca3dffc5aadbd7ce21) where ["k8s.io/component-base/cli"](https://pkg.go.dev/k8s.io/component-base/cli) was imported because of which vendor update was needed.

**Review by ffromani — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
