### PR TITLE
[KNI] add helper script to do carries

### PR DESCRIPTION
**Pull request by ffromani**
A "Carry" is when we merge and accept in our tree
a change which was not (yet) accepted u/s, either in the main branch or in a release branch.

Let's start adding a script to simplify carrying a full PR.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by yanirq** [comment]
This script is meant to run on you local dev environment or be triggered ?

**Comment by ffromani** [comment]
> This script is meant to run on you local dev environment or be triggered ?

Is meant to be run in our local dev env

**Pull request merged**
